INSERT INTO MYDOMAINID.PARENT (ID, NOME, SIBLING_ID) VALUES (
MYDOMAINID.SEQ_PARENT.NEXTVAL, 'Star Wars', 11
);
INSERT INTO MYDOMAINID.PARENT (ID, NOME, SIBLING_ID) VALUES (
MYDOMAINID.SEQ_PARENT.NEXTVAL, 'Deadpool', 22
);
INSERT INTO MYDOMAINID.PARENT (ID, NOME, SIBLING_ID) VALUES (
MYDOMAINID.SEQ_PARENT.NEXTVAL, 'Bob Nelson Foi À Praia', 33
);

INSERT INTO MYDOMAINID.CHILD (KEY, PARENT_ID, NAME, ANOTHER_CHILD_KEY)
VALUES (MYDOMAINID.SEQ_CHILD.NEXTVAL, 20001, '1SE child', NULL);

INSERT INTO MYDOMAINID.CHILD (KEY, PARENT_ID, NAME, ANOTHER_CHILD_KEY)
VALUES (MYDOMAINID.SEQ_CHILD.NEXTVAL, 20001, '2ND child', 50001);


INSERT INTO MYDOMAINID.GRANDCHILD (ID, PARENT_CHILD_KEY, NAME)
VALUES (MYDOMAINID.SEQ_GRANDCHILD.NEXTVAL, 50001, '1ST CHILD''S GRANDCHILDREN');